const Advance = require("../models/Advance.model");
const User = require("../models/User.model");
const { addTransaction } = require("../services/accountService");

// ===============================
// ADD ADVANCE (ADMIN ONLY)
// ===============================
exports.createAdvance = async (req, res) => {
  try {
    const { staffId, amount, date, notes, month } = req.body;

    console.log("Creating advance with:", { staffId, amount, date, notes, month });

    // Validate required fields
    if (!staffId) {
      return res.status(400).json({
        success: false,
        message: "Staff ID is required"
      });
    }

    if (!amount || amount <= 0) {
      return res.status(400).json({
        success: false,
        message: "Valid advance amount is required"
      });
    }

    if (!month) {
      return res.status(400).json({
        success: false,
        message: "Month is required (e.g., 'June 2026') - this determines when advance will be deducted"
      });
    }

    // Check staff exists
    const staff = await User.findById(staffId);
    if (!staff) {
      return res.status(404).json({
        success: false,
        message: "Staff not found"
      });
    }

    // Check if advance amount exceeds basic salary
    if (amount > (staff.basicSalary || 0)) {
      return res.status(400).json({
        success: false,
        message: `Advance amount (${amount}) cannot exceed basic salary (${staff.basicSalary || 0})`
      });
    }

    // Check if there's already a salary for this month (can't add advance after salary is processed)
    const Salary = require("../models/Salary.model");
    const existingSalary = await Salary.findOne({ 
      staffId: staffId, 
      month: month 
    });
    
    if (existingSalary) {
      return res.status(400).json({
        success: false,
        message: `Cannot add advance for ${month} because salary has already been processed for this month. Please adjust the salary instead.`
      });
    }

    // Create advance record - paymentNo will be auto-generated by the model
    const advance = await Advance.create({
      staffId,
      amount: Number(amount),
      date: date || new Date(),
      month: month,
      notes: notes || "",
      createdBy: req.user._id
      // paymentNo is auto-generated by the model's default function
    });

    console.log(`✅ Advance created for ${staff.fullName} - Amount: ${amount} for month: ${month}, Payment No: ${advance.paymentNo}`);

    // =====================
    // ADD TO ACCOUNT LEDGER
    // =====================
    try {
      await addTransaction({
        date: date || new Date(),
        invoiceNo: advance.paymentNo, // Use the auto-generated paymentNo
        description: `Salary Advance - ${staff.fullName} (Deduct from ${month})`,
        income: 0,
        expense: Number(amount),
        sourceModule: "advance",
        sourceId: advance._id,
        enteredBy: req.user._id,
        notes: notes || `Salary advance payment for ${staff.fullName} - will be deducted from ${month} salary`
      });
      console.log(`✅ Advance transaction added to accounts for ${staff.fullName} - LKR ${amount}`);
    } catch (accountErr) {
      console.error("Failed to add advance to account ledger:", accountErr);
      // Don't fail the advance creation if account recording fails
    }

    // Populate staff details for response
    const populatedAdvance = await Advance.findById(advance._id)
      .populate("staffId", "fullName username role basicSalary");

    res.status(201).json({
      success: true,
      message: "Advance added successfully",
      advance: populatedAdvance
    });
  } catch (error) {
    console.error("Error in createAdvance:", error);
    res.status(500).json({
      success: false,
      message: error.message
    });
  }
};

// ===============================
// GET ALL ADVANCES
// ===============================
exports.getAllAdvances = async (req, res) => {
  try {
    const advances = await Advance.find()
      .populate("staffId", "fullName username role basicSalary")
      .sort({ createdAt: -1 });

    res.json({
      success: true,
      advances
    });
  } catch (error) {
    console.error("Error in getAllAdvances:", error);
    res.status(500).json({
      success: false,
      message: error.message
    });
  }
};

// ===============================
// GET ADVANCES BY STAFF
// ===============================
exports.getAdvancesByStaff = async (req, res) => {
  try {
    const { staffId } = req.params;

    if (!staffId) {
      return res.status(400).json({
        success: false,
        message: "Staff ID is required"
      });
    }

    const advances = await Advance.find({ staffId })
      .populate("staffId", "fullName username role basicSalary")
      .sort({ date: -1 });

    res.json({
      success: true,
      advances
    });
  } catch (error) {
    console.error("Error in getAdvancesByStaff:", error);
    res.status(500).json({
      success: false,
      message: error.message
    });
  }
};

// ===============================
// GET ADVANCES BY STAFF AND MONTH
// ===============================
exports.getAdvancesByStaffAndMonth = async (req, res) => {
  try {
    const { staffId, month } = req.params;

    if (!staffId || !month) {
      return res.status(400).json({
        success: false,
        message: "Staff ID and month are required"
      });
    }

    const advances = await Advance.find({ 
      staffId, 
      month: month 
    }).populate("staffId", "fullName username role basicSalary");

    const totalAmount = advances.reduce((sum, adv) => sum + adv.amount, 0);

    res.json({
      success: true,
      advances,
      totalAmount,
      count: advances.length
    });
  } catch (error) {
    console.error("Error in getAdvancesByStaffAndMonth:", error);
    res.status(500).json({
      success: false,
      message: error.message
    });
  }
};

// ===============================
// GET ADVANCES BY MONTH (All staff)
// ===============================
exports.getAdvancesByMonth = async (req, res) => {
  try {
    const { month } = req.params;

    if (!month) {
      return res.status(400).json({
        success: false,
        message: "Month is required"
      });
    }

    const advances = await Advance.find({ month: month })
      .populate("staffId", "fullName username role basicSalary")
      .sort({ date: -1 });

    const totalAmount = advances.reduce((sum, adv) => sum + adv.amount, 0);

    res.json({
      success: true,
      month,
      advances,
      totalAmount,
      count: advances.length
    });
  } catch (error) {
    console.error("Error in getAdvancesByMonth:", error);
    res.status(500).json({
      success: false,
      message: error.message
    });
  }
};

// ===============================
// GET SINGLE ADVANCE
// ===============================
exports.getAdvanceById = async (req, res) => {
  try {
    const { id } = req.params;

    const advance = await Advance.findById(id)
      .populate("staffId", "fullName username role basicSalary")
      .populate("createdBy", "fullName username");

    if (!advance) {
      return res.status(404).json({
        success: false,
        message: "Advance not found"
      });
    }

    res.json({
      success: true,
      advance
    });
  } catch (error) {
    console.error("Error in getAdvanceById:", error);
    res.status(500).json({
      success: false,
      message: error.message
    });
  }
};

// ===============================
// UPDATE ADVANCE
// ===============================
exports.updateAdvance = async (req, res) => {
  try {
    const { id } = req.params;
    const { amount, date, notes, month } = req.body;

    const advance = await Advance.findById(id);
    if (!advance) {
      return res.status(404).json({
        success: false,
        message: "Advance not found"
      });
    }

    const oldAmount = advance.amount;
    const oldMonth = advance.month;

    // Check if salary already exists for the new month
    if (month && month !== oldMonth) {
      const Salary = require("../models/Salary.model");
      const existingSalary = await Salary.findOne({ 
        staffId: advance.staffId, 
        month: month 
      });
      
      if (existingSalary) {
        return res.status(400).json({
          success: false,
          message: `Cannot change month to ${month} because salary has already been processed for this month.`
        });
      }
    }

    // Update fields
    if (amount !== undefined) advance.amount = Number(amount);
    if (date) advance.date = date;
    if (notes !== undefined) advance.notes = notes;
    if (month) advance.month = month;

    await advance.save();

    console.log(`✅ Advance updated: ${advance.paymentNo} - Amount: ${oldAmount} -> ${advance.amount}, Month: ${oldMonth} -> ${advance.month}`);

    // If amount changed, update account ledger
    if (amount !== undefined && oldAmount !== amount) {
      try {
        const Account = require("../models/Account.model");
        await Account.findOneAndUpdate(
          { sourceModule: "advance", sourceId: advance._id },
          { 
            expense: Number(amount),
            notes: notes || `Salary advance updated - ${advance.paymentNo}`
          }
        );
        console.log(`✅ Advance account transaction updated: ${advance.paymentNo}`);
      } catch (accountErr) {
        console.error("Failed to update account ledger:", accountErr);
      }
    }

    const populatedAdvance = await Advance.findById(advance._id)
      .populate("staffId", "fullName username role basicSalary");

    res.json({
      success: true,
      message: "Advance updated successfully",
      advance: populatedAdvance
    });
  } catch (error) {
    console.error("Error in updateAdvance:", error);
    res.status(500).json({
      success: false,
      message: error.message
    });
  }
};

// ===============================
// DELETE ADVANCE (with account reversal)
// ===============================
exports.deleteAdvance = async (req, res) => {
  try {
    const { id } = req.params;

    const advance = await Advance.findById(id);
    if (!advance) {
      return res.status(404).json({
        success: false,
        message: "Advance not found"
      });
    }

    // Check if salary already exists for this month
    const Salary = require("../models/Salary.model");
    const existingSalary = await Salary.findOne({ 
      staffId: advance.staffId, 
      month: advance.month 
    });
    
    if (existingSalary) {
      return res.status(400).json({
        success: false,
        message: `Cannot delete advance for ${advance.month} because salary has already been processed for this month. Please adjust the salary instead.`
      });
    }

    console.log(`Deleting advance: ${advance.paymentNo} for amount ${advance.amount}`);

    // =====================
    // DELETE FROM ACCOUNT LEDGER
    // =====================
    try {
      const Account = require("../models/Account.model");
      const deleted = await Account.deleteOne({ 
        sourceModule: "advance", 
        sourceId: advance._id 
      });
      if (deleted.deletedCount > 0) {
        console.log(`✅ Advance account transaction deleted: ${advance.paymentNo}`);
      }
    } catch (accountErr) {
      console.error("Failed to delete from account ledger:", accountErr);
    }

    await Advance.findByIdAndDelete(id);

    res.json({
      success: true,
      message: "Advance deleted successfully"
    });
  } catch (error) {
    console.error("Error in deleteAdvance:", error);
    res.status(500).json({
      success: false,
      message: error.message
    });
  }
};

// ===============================
// GET TOTAL ADVANCES FOR STAFF (ALL TIME)
// ===============================
exports.getStaffAdvanceTotal = async (req, res) => {
  try {
    const { staffId } = req.params;

    const advances = await Advance.find({ staffId });
    const totalAmount = advances.reduce((sum, adv) => sum + adv.amount, 0);
    const advanceCount = advances.length;

    // Group by month
    const byMonth = {};
    advances.forEach(adv => {
      if (adv.month) {
        byMonth[adv.month] = (byMonth[adv.month] || 0) + adv.amount;
      }
    });

    res.json({
      success: true,
      staffId,
      totalAmount,
      advanceCount,
      byMonth,
      advances
    });
  } catch (error) {
    console.error("Error in getStaffAdvanceTotal:", error);
    res.status(500).json({
      success: false,
      message: error.message
    });
  }
};